# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: parallel_gripper_action_controller/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


panda_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    allow_nonzero_velocity_at_trajectory_end: true

gripper_controller:
  ros__parameters:
    joint: gripper_left_joint
